INSERT OR IGNORE INTO locations (
  source_key,
  retailer_name,
  address1,
  city,
  state,
  postal_code,
  latitude,
  longitude,
  has_video_lottery,
  has_video_poker,
  source_url,
  source_name,
  raw_payload,
  review_status,
  publish_status,
  confidence_score,
  last_seen_at
) VALUES
  (
    'seed-portland-001',
    'Lucky Stop Market',
    '123 Jackpot Ave',
    'Portland',
    'OR',
    '97201',
    45.5152,
    -122.6784,
    1,
    1,
    'https://example.com/source/1',
    'seed',
    '{"seed":true}',
    'approved',
    'live',
    1.0,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-salem-001',
    'Downtown Tavern',
    '456 Winner St',
    'Salem',
    'OR',
    '97301',
    44.9429,
    -123.0351,
    1,
    0,
    'https://example.com/source/2',
    'seed',
    '{"seed":true}',
    'approved',
    'live',
    1.0,
    CURRENT_TIMESTAMP
  );
